- src/samples/conference/package.json
- src/samples/conference/public/index.html
- src/samples/p2p/peercall.html
> Upgrade Socket.IO to 2.2.0.

- package.json
- src/.eslintrc.json
- src/sdk/base/base64.js
- src/sdk/base/codec.js
- src/sdk/base/event.js
- src/sdk/base/export.js
- src/sdk/base/logger.js
- src/sdk/base/mediaformat.js
- src/sdk/base/mediastream-factory.js
- src/sdk/base/publication.js
- src/sdk/base/sdputils.js
- src/sdk/base/stream.js
- src/sdk/base/utils.js
- src/sdk/conference/channel.js
- src/sdk/conference/client.js
- src/sdk/conference/error.js
- src/sdk/conference/export.js
- src/sdk/conference/info.js
- src/sdk/conference/mixedstream.js
- src/sdk/conference/participant.js
- src/sdk/conference/signaling.js
- src/sdk/conference/streamutils.js
- src/sdk/conference/subscription.js
- src/sdk/export.js
- src/sdk/p2p/error.js
- src/sdk/p2p/export.js
- src/sdk/p2p/p2pclient.js
- src/sdk/p2p/peerconnection-channel.js
> Update ESLint configuration and fix lint issues

- src/sdk/p2p/peerconnection-channel.js
> Fix tracksInfo is not defined.

- src/sdk/p2p/peerconnection-channel.js
> Fix stream stop event on Firefox.

- src/sdk/p2p/peerconnection-channel.js
The offer side and answer side used to be fixed during a session. It's a problem as we changed to unified plan because there might be more than one M section in SDP, but the answer side cannot add more m sections when it is needed.
> Sending offer from the endpoint which needs negotiation.

- docs/jsdoc/config.json
- package.json
- src/samples/conference/package.json
- src/samples/p2p/js/sc.websocket.js
- src/sdk/base/utils.js
See also: https://github.com/open-webrtc-toolkit/owt-server-p2p/pull/4
> Bump version number to 4.2 and rename ics-message to owt-message.

- src/samples/conference/public/scripts/rest-sample.js
Fix error when adding rtsp stream in url
> Fix error when adding rtsp stream in url

- src/sdk/base/utils.js
We'll drop plan-b support soon.
> Claim unified plan support in UA info.

- README.md
- src/samples/p2p/README.md
Also, fix some formatting and add some helpful text.
Signed-off-by: Geoff Gustafson <geoff@linux.intel.com>
> Fix port, line number reference in p2p sample README

- src/sdk/base/mediastream-factory.js
getDisplayMedia did not support exact value
> change constraints setting value

- src/samples/conference/public/scripts/index.js
- src/sdk/conference/signaling.js
Add click anchor in sample page for testing portal certificate
> Add click anchor in sample page for testing portal certificate

- src/sdk/rest/API.js
Expose analytics functions in REST
> Expose analytics functions in REST

- src/sdk/conference/channel.js
> improve publish method

- test/conference.jenkinsfile
- test/ubuntuconference.jenkinsfile
Update ubuntu's Jenkins file on JS to create a new podTemplate and not conflict with centos's podTemplate
> Update ubuntu's Jenkins file on JS to create a new podTemplate

- src/sdk/conference/channel.js
These are legacy configurations.
> Remove offerToReceiveAudio/offerToReceiveVideo.

- docs/mdfiles/changelog.md
- src/samples/conference/public/scripts/index.js
- src/sdk/base/publication.js
- src/sdk/base/stream.js
- src/sdk/conference/channel.js
- src/sdk/conference/client.js
- src/sdk/conference/mixedstream.js
- src/sdk/conference/streamutils.js
- src/sdk/conference/subscription.js
- Publish method accepts `RTCRtpEncodingParameters` as options.
- Upgrade conference protocol version to 1.1.
> Simulcast support

- src/sdk/conference/channel.js
- src/sdk/conference/streamutils.js
To fix issues #208, #209, #210
> Fix rid setting in signaling

- src/sdk/conference/channel.js
Enable simulcast publish on Firefox
> Enable simulcast publish on Firefox

- src/sdk/base/sdputils.js
- src/sdk/conference/channel.js
Add legacy simulcast for safari
> Add legacy simulcast for safari

- src/sdk/base/codec.js
> Add description for VideoCodec.

- docs/jsdoc/config.json
- docs/mdfiles/simulcast.md
c46d20eba3019f0c7ea9e2a6f1269a6844a6d80e
> Add document for simulcast

- docs/mdfiles/simulcast.md
> Update simulcast document

- docs/mdfiles/index.md
> Update browser versions

- test/conference.jenkinsfile
- test/ubuntuconference.jenkinsfile
> fix pipeline for pv

- test/conference.jenkinsfile
- test/ubuntuconference.jenkinsfile
> add simucast stage

- test/conference.jenkinsfile
- test/ubuntuconference.jenkinsfile
> Fix stage name

- test/conference.jenkinsfile
- test/ubuntuconference.jenkinsfile
> delete not use stage

- src/sdk/p2p/peerconnection-channel.js
> Listen ontrack event on Safari.

- scripts/Gruntfile.js
- src/.eslintrc.json
- src/sdk/base/codec.js
- src/sdk/base/event.js
- src/sdk/base/mediaformat.js
- src/sdk/base/mediastream-factory.js
- src/sdk/base/publication.js
- src/sdk/base/stream.js
- src/sdk/conference/channel.js
- src/sdk/conference/mixedstream.js
- src/sdk/conference/streamutils.js
- src/sdk/p2p/peerconnection-channel.js
> Fix ESLint errors and enforce ESLint rules by default

- src/sdk/base/mediastream-factory.js
- src/sdk/conference/streamutils.js
- src/sdk/p2p/peerconnection-channel.js
This PR includes some commits picked from master to 4.3.x for 4.3.1 release.
> Pick a few commits to 4.3.x.

- src/samples/.eslintrc.json
- src/samples/p2p/README.md
- src/samples/p2p/js/peercall.js
- src/samples/p2p/js/sc.websocket.js
- src/samples/p2p/peercall.html
I think my main goal here was just to move the configurable part of the code up to the top of the file. :)
> Refactor p2p sample

- package-lock.json
- package.json
This change is generated by running `npm update`.
> Upgrade npm dependencies.

- src/samples/p2p/js/sc.websocket.js
Ref: https://github.com/open-webrtc-toolkit/owt-server-p2p/issues/24
> Move authentication info from query string to socket.io message.

- docs/design/webtransport.md
- docs/mdfiles/changelog.md
- package.json
- scripts/Gruntfile.js
- src/samples/conference/README.md
- src/samples/conference/package-lock.json
- src/samples/conference/public/quic.html
- src/samples/conference/public/scripts/quic.js
- src/sdk/base/export.js
- src/sdk/base/publication.js
- src/sdk/base/stream.js
- src/sdk/base/transport.js
- src/sdk/conference/channel.js
- src/sdk/conference/client.js
- src/sdk/conference/quicconnection.js
- src/sdk/conference/subscription.js
This PR adds WebTransport - QuicTransport server for conference mode. It depends on https://github.com/open-webrtc-toolkit/owt-server/pull/113.
> Add WebTransport support.

- src/sdk/base/stream.js
Fixes https://github.com/open-webrtc-toolkit/owt-server/issues/760.
> Update the description of RemoteStream's ended event.

- src/sdk/base/stream.js
These two objects are only defined in limited environments.
> Check availability of SendStream and BidirectionalStream.

- src/samples/conference/package-lock.json
- src/samples/conference/package.json
- Remove socket.io as it's not used.
- Bump version number to 5.0.
- Update name.
> Update package.json for conference sample.

- package-lock.json
- src/samples/conference/public/index.html
- src/samples/conference/public/quic.html
- src/samples/p2p/peercall.html
- test/p2ptest/fetch_dependencies.py
Please merge this PR without squash.
> Pick two changes to 5.0.x branch

- src/sdk/conference/channel.js
- test/unit/resources/scripts/conference.js
scalabilityMode is defined in webrtc-svc.
> Add one more condition for testing RtpEncodingParameters.

- test/conference.jenkinsfile
- test/ubuntuconference.jenkinsfile
Unit tests are covered by GitHub Actions workflow.
> Remove unit tests from Jenkins pipelines.

- src/sdk/base/utils.js
- src/sdk/conference/channel.js
- src/sdk/p2p/peerconnection-channel.js
Ref: https://github.com/open-webrtc-toolkit/owt-client-javascript/issues/461
> Remove plan B support and remove some legacy API calls.

- src/sdk/p2p/peerconnection-channel.js
removeTrack sets transceiver's direction to inactive, which doesn't
cause ended event of remote tracks to be fired. This change stops a
transceiver when publication.stop is called.
> Fix ended event on remote streams.

- test/ubuntu_p2p.jenkinsfile
add jenkinsfile for p2ptest on k8s
> add jenkinsfile for p2ptest on k8s

- scripts/Gruntfile.js
This repo uses ESLint for linting.
Fix #528.
> Remove jshint task.

- .github/workflows/ci.yaml
This change makes the workflow follow the principle of least privilege.
> Run GitHub workflow with read permission.
