- src/sdk/base/codec.js
- src/sdk/base/mediaformat.js
- src/sdk/base/publication.js
- src/sdk/conference/mixedstream.js
- src/sdk/conference/subscription.js
- src/sdk/p2p/p2pclient.js
> Fix some documentation issues.

- docs/mdfiles/index.md
This PR also removes a section for migration from 3.x.
> Add a section for privacy in documentation.

- src/samples/conference/public/scripts/index.js
- src/sdk/conference/signaling.js
Add click anchor in sample page for testing portal certificate
> Add click anchor in sample page for testing portal certificate

- src/sdk/conference/channel.js
This change is based on commit 21bdf18be35cfbb1bfecc71a381f32d89efd0c4b.
> Fire ended event when PeerConnection's connectionState changed to closed or failed.

- src/sdk/base/publication.js
> The ended event may not be fired on Safari after calling Publication.stop().

- scripts/Gruntfile.js
This command was supported in old versions, but replaced by `grunt dev` in 4.x. It still useful when a debug version of SDK is need.
Fix #148 and #319.
> Re-enable grunt debug.

- src/samples/conference/public/index.html
- src/samples/p2p/peercall.html
- test/p2ptest/fetch_dependencies.py
- test/p2ptest/karma_config/chrome.config.js
- test/p2ptest/karma_config/firefox.config.js
- test/p2ptest/karma_config/safari.config.js
Conference sample still loads adapter.js when running on Edge.
> Remove adapter.js.

- src/sdk/p2p/p2pclient.js
- src/sdk/p2p/peerconnection-channel.js
Sometimes system info and close message may be sent to remote side more than once. It caused PeerConnection to be closed if a close message is sent in the middle of a call.
> Send system info and close message no more than once.

- docs/design/owt_with_webrtc_apis.md
> Add design review for exposing RTCRtpTransceiver.

- src/sdk/base/utils.js
- src/sdk/p2p/peerconnection-channel.js
Ref: https://github.com/open-webrtc-toolkit/owt-server-p2p/issues/17.
> Remove acknowledgements for data channel messages.

- src/sdk/conference/streamutils.js
It fixes an error caused by reading properties of `undefined`.
> Check optional properties of video info before creating VideoSubscriptionCapabilities.

- src/sdk/base/mediastream-factory.js
Safari supports `getDisplayMedia`.
> Allow creating screen sharing stream on Safari.

- package-lock.json
This change is made by running `npm audit fix`. `kind-of` is manually upgraded from 6.0.x to 6.0.3.
> Upgrade npm dependencies.

- src/samples/p2p/js/peercall.js
- src/samples/p2p/peercall.html
Remote stream is muted by default. This is a little confusion as audio will not work without manually changing the demo's HTML. 
Alternative is to provide explicit muting controls. That could be an overkill as audio can be easily muted on the system.
> Add a Mute toggle for remote audio stream

- test/conference.jenkinsfile
- test/p2p.jenkinsfile
- test/ubuntuconference.jenkinsfile
update 4.2.x and p2p jenkinsfile
> update 4.2.x and p2p jenkinsfile

- test/unit/resources/scripts/p2p.js
Case "Send a message to a remote endpoint should be resolved" fails sometimes during check in test and nightly test. It's probably cased by signaling messages for last case don't get flushed in time. This change gives signaling server a chance to send out all messages before the next case.
> Clean event queue after each case.

- src/sdk/base/logger.js
Timestamps make it easy to debug issues happen with specific call sequence.
> Add timestamp to logs.

- src/sdk/p2p/peerconnection-channel.js
Cached remote ICE candidate can be added to `PeerConnection` when signaling state is 'have-remote-offer' when current endpoint is answerer, or 'stable' when current endpoint is offerer.
> Fix an issue to prevent from lossing cached remote ICE candidates.

- src/sdk/conference/channel.js
Since server supports bundle, we can safely set it to max-bundle. It also fixes the issue that paced sender is paused during renegotiation.
Fixes #435.
> Set bundle policy to max-bundle for conference mode.

- src/sdk/conference/channel.js
QA observed an issue when mixing a stream published from Firefox with max-bundle.
> Set bundle policy to max-bundle on Chrome only.

- docs/design/webtransport.md
- docs/jsdoc/config.json
- src/sdk/conference/client.js
- src/sdk/conference/quicconnection.js
`QuicTransport` was merged to `WebTransport`. This change updates some calls to comply with the latest spec.
This change also resolves join after authentication is passed for WebTransport.
> Use WebTransport instead of QuicTransport.

- .github/workflows/ci.yaml
- package-lock.json
- package.json
- test/unit/karma/ci.config.js
- test/unit/resources/scripts/base.js
- test/unit/resources/scripts/fake-p2p-signaling.js
- test/unit/resources/scripts/p2p.js
Add unit tests to CI using GitHub Actions. It runs on Chrome(Ubuntu, Windows, macOS), Firefox(Ubuntu, Windows, macOS) and Edge(Windows). Safari is not in the list because I don't find a solution to figure out the getUserMedia prompt yet.
Fixes #321.
> Enable CI using Github Actions

- docs/design/perfect_negotiation.md
- src/sdk/p2p/p2pclient.js
- src/sdk/p2p/peerconnection-channel.js
- test/unit/resources/scripts/fake-p2p-signaling.js
- test/unit/resources/scripts/p2p.js
Implement [perfect negotiation](https://w3c.github.io/webrtc-pc/#perfect-negotiation-example) to avoid collision.
> Implement perfect negotiation.

- src/sdk/base/codec.js
AV1(AV1X) encoder is only available on Chrome >= 90.
> Add AV1 to video codec enumeration.

- src/sdk/p2p/peerconnection-channel.js
Sending the argument passed to setLocalDescription() is not always the correct thing to do, if there are new offers incoming or a rollback occurred. Instead, send the PeerConnection's localDescription (not current or pending, PeerConnection knows which to use)
> Send localDescription, not local variable

- src/sdk/p2p/peerconnection-channel.js
When the impolite side receives offer after `setLocalDescription`, before it's
resolved, it sets both local description and remote description. Its
signaling state changes from stable to have-local-offer, to stable, to
have-remote-offer. It doesn't comply with the behavior of impolite side
described in perfect negotiation, which is ignoring the remote
description.
Test: P2P case WebRTC collision should be resolved.
Fix #484.
> Don't set remote description when a setLocalDescription is not resolved.

- docs/mdfiles/changelog.md
- src/samples/conference/public/scripts/index.js
- src/sdk/base/stream.js
- src/sdk/conference/channel.js
- src/sdk/conference/subscription.js
When subscribe a stream in conference mode, the subscribed stream no
longer associated with RemoteStream. It allows a RemoteStream to be
subscribed multiple times. It also allows a subscription has audio and
video track from different remote streams.
Since the signaling protocol defined by server side does not provide an
ID for a track, the SDK usually use stream ID + track kind to identify a
track. The stream ID and track ID mentioned in conference mode indicate
the ID assigned by conference sever, they could be different from
MediaStream ID and MediaStreamTrack ID.
> Subscribed streams are associated with subscriptions.

- docs/design/owt_with_webrtc_apis.md
- docs/mdfiles/changelog.md
- src/.eslintrc.json
- src/samples/conference/public/scripts/index.js
- src/sdk/conference/channel.js
- src/sdk/conference/client.js
This change allows developers to publish a stream with specific `RTCTransceiver`s. See https://github.com/open-webrtc-toolkit/owt-client-javascript/blob/master/docs/design/owt_with_webrtc_apis.md for detailed design.
> Publish with RTCRtpTransceivers.

- docs/design/owt_with_webrtc_apis.md
- src/sdk/p2p/p2pclient.js
- src/sdk/p2p/peerconnection-channel.js
- test/unit/resources/scripts/p2p.js
This change also adds an API to get PeerConnection for a given remote
endpoint. Since the P2P mode heavily depends on remote endpoint's
implementation. Using WebRTC APIs directly in P2P mode is not
recommended.
> Publication.rtpTransceivers returns transceivers in P2P mode.

- src/sdk/base/logger.js
Default log level for production environment. If developers want collect
more information, please change log level manually.
> Set default log level to error.

- src/sdk/conference/channel.js
- src/sdk/conference/client.js
- test/unit/resources/scripts/conference.js
This change allows application to get `PeerConnection` before publishing or subscribing. Then the application can create `RTCRtpTransceiver`s on the `PeerConnection` returned, and publish a stream with `RTCRtpTransceiver`s pre-configurated.
> Create PeerConnection when PeerConnectionChannel is created.

- src/sdk/p2p/p2pclient.js
Old clients don't have connection Id. Disable perfect negotiation if remote client is not supported.
> Fix a compatibility issue with old clients.

- test/unit/resources/scripts/p2p.js
Temporary disable this case to allow new changes to be merged. An issue has been reported https://github.com/open-webrtc-toolkit/owt-client-javascript/issues/589, to be fixed later.
> Temporary disable "WebRTC collision should be resolved.".
